# Storm Typing Results Notebook

In [1]:
import pandas as pd
import scrapbook as sb
from IPython.display import HTML
from notebook_utils import *

In [2]:

notebooks_folder_path = "notebooks"
notebook_paths = get_notebook_paths(notebooks_folder_path)
all_data = process_multiday_notebooks(notebook_paths)

In [3]:
all_data_with_links = convert_paths_to_html_links(all_data, notebook_paths)

## Synoptic Storms

In [4]:
HTML(
    all_data[all_data["likely_storm_type"] == "Synoptic_Storm"].to_html(
        escape=False
    )
)

## Mesoscale Storms

In [5]:
HTML(all_data[all_data["likely_storm_type"] == "Mesoscale_Storm"].to_html(escape=False))

## Atmospheric River

In [6]:
HTML(all_data[all_data["likely_storm_type"] == "Atmospheric_River"].to_html(escape=False))

## Local Storms

In [7]:
HTML(all_data[all_data["likely_storm_type"] == "Local_Storm"].to_html(escape=False))

## Hybrid

In [8]:
HTML(all_data[all_data["likely_storm_type"] == "hybrid"].to_html(escape=False))